/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JSwings;

/**
 *
 * @author erpys
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Baddstudent = new javax.swing.JButton();
        Bliststudents = new javax.swing.JButton();
        Bsearchstudentdni = new javax.swing.JButton();
        Bdeletestudent = new javax.swing.JButton();
        Bexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Baddstudent.setBackground(new java.awt.Color(125, 255, 15));
        Baddstudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Baddstudent.setText("Add a new student");
        Baddstudent.setBorder(null);
        Baddstudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Baddstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaddstudentActionPerformed(evt);
            }
        });

        Bliststudents.setBackground(new java.awt.Color(110, 188, 255));
        Bliststudents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Bliststudents.setText("Show list of students");
        Bliststudents.setBorder(null);
        Bliststudents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bliststudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BliststudentsActionPerformed(evt);
            }
        });

        Bsearchstudentdni.setBackground(new java.awt.Color(255, 255, 101));
        Bsearchstudentdni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Bsearchstudentdni.setText("Search a student by dni");
        Bsearchstudentdni.setBorder(null);
        Bsearchstudentdni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bsearchstudentdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsearchstudentdniActionPerformed(evt);
            }
        });

        Bdeletestudent.setBackground(new java.awt.Color(255, 90, 90));
        Bdeletestudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Bdeletestudent.setText(" Delete a student");
        Bdeletestudent.setBorder(null);
        Bdeletestudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bdeletestudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdeletestudentActionPerformed(evt);
            }
        });

        Bexit.setBackground(new java.awt.Color(40, 40, 40));
        Bexit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Bexit.setForeground(new java.awt.Color(255, 255, 255));
        Bexit.setText("Exit");
        Bexit.setBorder(null);
        Bexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Baddstudent, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(Bdeletestudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bsearchstudentdni, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(Bliststudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Baddstudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bliststudents, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bdeletestudent, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(Bsearchstudentdni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BexitActionPerformed
        this.dispose();
    }//GEN-LAST:event_BexitActionPerformed

    private void BaddstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaddstudentActionPerformed
        new AddStudent().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BaddstudentActionPerformed

    private void BliststudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BliststudentsActionPerformed
        new ListStudents().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BliststudentsActionPerformed

    private void BsearchstudentdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsearchstudentdniActionPerformed
        new SearchByDni().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BsearchstudentdniActionPerformed

    private void BdeletestudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdeletestudentActionPerformed
        new DeleteStudent().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BdeletestudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Baddstudent;
    private javax.swing.JButton Bdeletestudent;
    private javax.swing.JButton Bexit;
    private javax.swing.JButton Bliststudents;
    private javax.swing.JButton Bsearchstudentdni;
    // End of variables declaration//GEN-END:variables
}
